dist: xenial

services:
  - docker

language: python
python:
  - "3.7"

jobs:
  include:
    - script:
        - docker-compose -v
        - docker -v
        - docker-compose -f local.yml build
        - docker-compose -f local.yml up -d
        - docker-compose -f local.yml run --rm django pytest
        - docker-compose -f local.yml logs
      name: "Django Test"

    - script: docker build -t cookiecutter:1.0 .
      name: "Dockerfile Deploy"
